In [65]:
import pandas as pd 
import numpy as np 
import matplotlib.pyplot as plt 
import warnings
warnings.filterwarnings("ignore")

In [66]:
df = pd.read_csv(r"D:\Amaan_Behlim\03_Projects\Ml project\04_NLP\data\raw\movies_metadata.csv")
df.head()

,adult,belongs_to_collection,budget,genres,homepage,id,imdb_id,original_language,original_title,overview,...,release_date,revenue,runtime,spoken_languages,status,tagline,title,video,vote_average,vote_count
0,False,"{'id': 10194, 'name': 'Toy Story Collection', ...",30000000,"[{'id': 16, 'name': 'Animation'}, {'id': 35, '...",http://toystory.disney.com/toy-story,862,tt0114709,en,Toy Story,"Led by Woody, Andy's toys live happily in his ...",...,1995-10-30,373554033.0,81.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,NaN,Toy Story,False,7.7,5415.0
1,False,NaN,65000000,"[{'id': 12, 'name': 'Adventure'}, {'id': 14, '...",NaN,8844,tt0113497,en,Jumanji,When siblings Judy and Peter discover an encha...,...,1995-12-15,262797249.0,104.0,"[{'iso_639_1': 'en', 'name': 'English'}, {'iso...",Released,Roll the dice and unleash the excitement!,Jumanji,False,6.9,2413.0
2,False,"{'id': 119050, 'name': 'Grumpy Old Men Collect...",0,"[{'id': 10749, 'name': 'Romance'}, {'id': 35, ...",NaN,15602,tt0113228,en,Grumpier Old Men,A family wedding reignites the ancient feud be...,...,1995-12-22,0.0,101.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,Still Yelling. Still Fighting. Still Ready for...,Grumpier Old Men,False,6.5,92.0
3,False,NaN,16000000,"[{'id': 35, 'name': 'Comedy'}, {'id': 18, 'nam...",NaN,31357,tt0114885,en,Waiting to Exhale,"Cheated on, mistreated and stepped on, the wom...",...,1995-12-22,81452156.0,127.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,Friends are the people who let you be yourself...,Waiting to Exhale,False,6.1,34.0
4,False,"{'id': 96871, 'name': 'Father of the Bride Col...",0,"[{'id': 35, 'name': 'Comedy'}]",NaN,11862,tt0113041,en,Father of the Bride Part II,Just when George Banks has recovered from his ...,...,1995-02-10,76578911.0,106.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,Just When His World Is Back To Normal... He's ...,Father of the Bride Part II,False,5.7,173.0

In [67]:
df.columns

Index(['adult', 'belongs_to_collection', 'budget', 'genres', 'homepage', 'id',
       'imdb_id', 'original_language', 'original_title', 'overview',
       'popularity', 'poster_path', 'production_companies',
       'production_countries', 'release_date', 'revenue', 'runtime',
       'spoken_languages', 'status', 'tagline', 'title', 'video',
       'vote_average', 'vote_count'],
      dtype='str')

In [68]:
df.duplicated().sum()
df = df.drop_duplicates().reset_index(drop=True)

In [69]:
df = df[['title','genres','overview','tagline','popularity','production_companies','vote_average']]
df.head()

,title,genres,overview,tagline,popularity,production_companies,vote_average
0,Toy Story,"[{'id': 16, 'name': 'Animation'}, {'id': 35, '...","Led by Woody, Andy's toys live happily in his ...",NaN,21.946943,"[{'name': 'Pixar Animation Studios', 'id': 3}]",7.7
1,Jumanji,"[{'id': 12, 'name': 'Adventure'}, {'id': 14, '...",When siblings Judy and Peter discover an encha...,Roll the dice and unleash the excitement!,17.015539,"[{'name': 'TriStar Pictures', 'id': 559}, {'na...",6.9
2,Grumpier Old Men,"[{'id': 10749, 'name': 'Romance'}, {'id': 35, ...",A family wedding reignites the ancient feud be...,Still Yelling. Still Fighting. Still Ready for...,11.7129,"[{'name': 'Warner Bros.', 'id': 6194}, {'name'...",6.5
3,Waiting to Exhale,"[{'id': 35, 'name': 'Comedy'}, {'id': 18, 'nam...","Cheated on, mistreated and stepped on, the wom...",Friends are the people who let you be yourself...,3.859495,[{'name': 'Twentieth Century Fox Film Corporat...,6.1
4,Father of the Bride Part II,"[{'id': 35, 'name': 'Comedy'}]",Just when George Banks has recovered from his ...,Just When His World Is Back To Normal... He's ...,8.387519,"[{'name': 'Sandollar Productions', 'id': 5842}...",5.7

In [70]:
df.isnull().sum()

title                       6
genres                      0
overview                  954
tagline                 25045
popularity                  5
production_companies        3
vote_average                6
dtype: int64

In [71]:
df = df.dropna(subset=['title'])

In [72]:
df.isnull().sum()

title                       0
genres                      0
overview                  954
tagline                 25039
popularity                  0
production_companies        0
vote_average                0
dtype: int64

In [73]:
df['overview'] = df['overview'].fillna(" ")

In [74]:
df.head()

,title,genres,overview,tagline,popularity,production_companies,vote_average
0,Toy Story,"[{'id': 16, 'name': 'Animation'}, {'id': 35, '...","Led by Woody, Andy's toys live happily in his ...",NaN,21.946943,"[{'name': 'Pixar Animation Studios', 'id': 3}]",7.7
1,Jumanji,"[{'id': 12, 'name': 'Adventure'}, {'id': 14, '...",When siblings Judy and Peter discover an encha...,Roll the dice and unleash the excitement!,17.015539,"[{'name': 'TriStar Pictures', 'id': 559}, {'na...",6.9
2,Grumpier Old Men,"[{'id': 10749, 'name': 'Romance'}, {'id': 35, ...",A family wedding reignites the ancient feud be...,Still Yelling. Still Fighting. Still Ready for...,11.7129,"[{'name': 'Warner Bros.', 'id': 6194}, {'name'...",6.5
3,Waiting to Exhale,"[{'id': 35, 'name': 'Comedy'}, {'id': 18, 'nam...","Cheated on, mistreated and stepped on, the wom...",Friends are the people who let you be yourself...,3.859495,[{'name': 'Twentieth Century Fox Film Corporat...,6.1
4,Father of the Bride Part II,"[{'id': 35, 'name': 'Comedy'}]",Just when George Banks has recovered from his ...,Just When His World Is Back To Normal... He's ...,8.387519,"[{'name': 'Sandollar Productions', 'id': 5842}...",5.7

In [75]:
import ast
df['genres'] = df['genres'].apply(lambda x:" ".join([i['name'] for i in ast.literal_eval(x)]))
df.head()

,title,genres,overview,tagline,popularity,production_companies,vote_average
0,Toy Story,Animation Comedy Family,"Led by Woody, Andy's toys live happily in his ...",NaN,21.946943,"[{'name': 'Pixar Animation Studios', 'id': 3}]",7.7
1,Jumanji,Adventure Fantasy Family,When siblings Judy and Peter discover an encha...,Roll the dice and unleash the excitement!,17.015539,"[{'name': 'TriStar Pictures', 'id': 559}, {'na...",6.9
2,Grumpier Old Men,Romance Comedy,A family wedding reignites the ancient feud be...,Still Yelling. Still Fighting. Still Ready for...,11.7129,"[{'name': 'Warner Bros.', 'id': 6194}, {'name'...",6.5
3,Waiting to Exhale,Comedy Drama Romance,"Cheated on, mistreated and stepped on, the wom...",Friends are the people who let you be yourself...,3.859495,[{'name': 'Twentieth Century Fox Film Corporat...,6.1
4,Father of the Bride Part II,Comedy,Just when George Banks has recovered from his ...,Just When His World Is Back To Normal... He's ...,8.387519,"[{'name': 'Sandollar Productions', 'id': 5842}...",5.7

In [76]:
df['tagline'] = df['tagline'].fillna(' ')

In [77]:
df['production_companies'] = df['production_companies'].apply(lambda x:" ".join([i['name'] for i in ast.literal_eval(x)]))

In [78]:
df.head()

,title,genres,overview,tagline,popularity,production_companies,vote_average
0,Toy Story,Animation Comedy Family,"Led by Woody, Andy's toys live happily in his ...",,21.946943,Pixar Animation Studios,7.7
1,Jumanji,Adventure Fantasy Family,When siblings Judy and Peter discover an encha...,Roll the dice and unleash the excitement!,17.015539,TriStar Pictures Teitler Film Interscope Commu...,6.9
2,Grumpier Old Men,Romance Comedy,A family wedding reignites the ancient feud be...,Still Yelling. Still Fighting. Still Ready for...,11.7129,Warner Bros. Lancaster Gate,6.5
3,Waiting to Exhale,Comedy Drama Romance,"Cheated on, mistreated and stepped on, the wom...",Friends are the people who let you be yourself...,3.859495,Twentieth Century Fox Film Corporation,6.1
4,Father of the Bride Part II,Comedy,Just when George Banks has recovered from his ...,Just When His World Is Back To Normal... He's ...,8.387519,Sandollar Productions Touchstone Pictures,5.7

In [79]:
df['tags'] = df['overview'] + " " + df['genres'] + " " + df['tagline'] + " " + df['production_companies']

In [80]:
df.head()

,title,genres,overview,tagline,popularity,production_companies,vote_average,tags
0,Toy Story,Animation Comedy Family,"Led by Woody, Andy's toys live happily in his ...",,21.946943,Pixar Animation Studios,7.7,"Led by Woody, Andy's toys live happily in his ..."
1,Jumanji,Adventure Fantasy Family,When siblings Judy and Peter discover an encha...,Roll the dice and unleash the excitement!,17.015539,TriStar Pictures Teitler Film Interscope Commu...,6.9,When siblings Judy and Peter discover an encha...
2,Grumpier Old Men,Romance Comedy,A family wedding reignites the ancient feud be...,Still Yelling. Still Fighting. Still Ready for...,11.7129,Warner Bros. Lancaster Gate,6.5,A family wedding reignites the ancient feud be...
3,Waiting to Exhale,Comedy Drama Romance,"Cheated on, mistreated and stepped on, the wom...",Friends are the people who let you be yourself...,3.859495,Twentieth Century Fox Film Corporation,6.1,"Cheated on, mistreated and stepped on, the wom..."
4,Father of the Bride Part II,Comedy,Just when George Banks has recovered from his ...,Just When His World Is Back To Normal... He's ...,8.387519,Sandollar Productions Touchstone Pictures,5.7,Just when George Banks has recovered from his ...

In [81]:
df['tags'][1]

"When siblings Judy and Peter discover an enchanted board game that opens the door to a magical world, they unwittingly invite Alan -- an adult who's been trapped inside the game for 26 years -- into their living room. Alan's only hope for freedom is to finish the game, which proves risky as all three find themselves running from giant rhinoceroses, evil monkeys and other terrifying creatures. Adventure Fantasy Family Roll the dice and unleash the excitement! TriStar Pictures Teitler Film Interscope Communications"

# NLP

In [82]:
# !pip install nltk

In [83]:
import re
from nltk.corpus import stopwords
from nltk.stem import WordNetLemmatizer

In [84]:
import nltk
nltk.download('stopwords')
nltk.download('wordnet')

[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\behli\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!
[nltk_data] Downloading package wordnet to
[nltk_data]     C:\Users\behli\AppData\Roaming\nltk_data...
[nltk_data]   Package wordnet is already up-to-date!

True

In [85]:
stop_words = set(stopwords.words("english"))
lemit = WordNetLemmatizer()

In [ ]:
def processor(text):
    text = str(text).lower()
    text = re.sub(r'[^a-zA-Z\s]','',text)
    words = text.split()
    words = [word for word in words if word not in stop_words] 
    words = [lemit.lemmatize(word) for word in words]
    return " ".join(words)
# def preprocess_text(text):
#       #lowercase
#   text = str(text).lower()
#   #removed the punctuations
#   text = re.sub(r'[^a-zA-Z\s]', '', text)

#   words = text.split()
#   #remove stopwords
#   words = [word for word in words if word not in stop_words]

#   #lemmatize
#   words = [lemit.lemmatize(word) for word in words]

#   return " ".join(words)

In [101]:
df['tags'] = df['tags'].apply(processor)

In [102]:
df['tags'][1]

'sibling judy peter discover enchanted board game open door magical world unwittingly invite alan adult trapped inside game year living room alans hope freedom finish game prof risky three find running giant rhinoceros evil monkey terrifying creature adventure fantasy family roll dice unleash excitement tristar picture teitler film interscope communication'